version: '3.4'

services:
  taskmanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # To configure https: https://443
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      # - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro